on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Build image
      - name: Build docker image
        run: docker build . -t pavelgeorgiev/ttt

  job2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Stub
        run: echo Done

  job_master_only:
    if: github.ref == 'refs/heads/master'
    needs: [job1, job2]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Stub
        run: echo Done job_master_only



  finally:
    if: always()
    needs: [job1, job2, job_master_only]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Stub
        run: echo Done finally
