on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Build image
      - name: Build docker image
        run: docker build . -t pavelgeorgiev/ttt

      - if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # If push to master, publish 'latest' image tag
      - if: github.ref == 'refs/heads/master'
        name: Publish latest
        run: docker push pavelgeorgiev/ttt

        # If push to master, publish 'latest' image tag
      - if: startsWith(github.ref, 'refs/tags/')
        name: Publish release tag
        # shell: bash
        run: |
          IMG_TAG=$(cut -d/ -f3 <<< ${{github.ref}})
          docker tag pavelgeorgiev/ttt pavelgeorgiev/ttt:$IMG_TAG
          docker push pavelgeorgiev/ttt:$IMG_TAG
