on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Build image
      - run: echo done job1

  job2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Stub
        run: exit 0

  job_master_only:
    if: github.ref == 'refs/heads/master'
    needs: [job1, job2]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Stub
        run: echo Done job_master_only



  finally_success:
    if: success() # redundant
    needs: [job1, job2, job_master_only]
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: homoluctus/slatify@master
        if: always() # redundant
        with:
          job_name: '(run id: ${{ github.run_id }})'
          type: success
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}

  finally_failure:
    if: "! success()"
    needs: [job1, job2, job_master_only]
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: homoluctus/slatify@master
        if: always() # is it needed?
        with:
          job_name: '(run id: ${{ github.run_id }})'
          type: failure
          mention: here
          mention_if: true
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}

