on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build docker image
        run:  |
          echo ${{ github.event.push }}
          echo ==========
          echo ${{ github.ref }}
          echo ==========
          echo ${{ github.event_name }}
