on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build docker image
        run:  |
          echo ${{ github.event }}
          echo ==========
          echo ${{ github }}
