on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build docker image
        run: docker build . -t ${{ github.repository }}
  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Publish docker image
        run: |
          docker image ls
          echo ${{ github.event_name }}
